import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:hydrated_bloc/hydrated_bloc.dart';
import 'package:path_provider/path_provider.dart';
import 'package:spotifyapp/core/configs/theme/app_theme.dart';
import 'package:spotifyapp/core/utils/link_handler.dart';
import 'package:spotifyapp/presentation/choose_mode/bloc/theme_cubit.dart';
import 'package:spotifyapp/presentation/home/page/home_page.dart';
import 'package:spotifyapp/presentation/splash/pages/splash.dart';
import 'package:firebase_core/firebase_core.dart';
//import 'firebase_options.dart'; // Ensure this file is present and generated by flutterfire configure
//import 'package:cloud_firestore/cloud_firestore.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Set up HydratedBloc storage
  HydratedBloc.storage = await HydratedStorage.build(
    storageDirectory: kIsWeb
        ? HydratedStorage.webStorageDirectory
        : await getApplicationDocumentsDirectory(),
  );
  await Firebase.initializeApp(
    options: const FirebaseOptions(
      apiKey: "AIzaSyAtggoyhimvqsyXp1ouowhq6kbZekoPfK0",
      authDomain: "spotapp-1fa6b.firebaseapp.com",
      projectId: "spotapp-1fa6b",
      storageBucket: "spotapp-1fa6b.firebasestorage.app",
      messagingSenderId: "1002606467368",
      appId: "1:1002606467368:web:c05811fdf8f5e6f3fc981d",
    ),
  );

  print("Firebase has been initialized successfully");
  incomingLinks();
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiBlocProvider(
      providers: [BlocProvider(create: (_) => ThemeCubit())],
      child: BlocBuilder<ThemeCubit, ThemeMode>(
        builder: (context, mode) => MaterialApp(
          theme: AppTheme.lightTheme,
          darkTheme: AppTheme.darkTheme,
          themeMode: mode,
          debugShowCheckedModeBanner: false,
          home: const SplashPage(),
          navigatorKey: navigatorKey,
        ),
      ),
    );
  }
}

final GlobalKey<NavigatorState> navigatorKey = GlobalKey<NavigatorState>();

void navigateToHome(String accessToken) {
  navigatorKey.currentState?.pushReplacement(
    MaterialPageRoute(
      builder: (context) => HomePage(accessToken: accessToken),
    ),
  );
}
